[package]
name = "nomad-app"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.25"
pulldown-cmark = "0.9"
tui = { version = "0.19", default-features = false, features = ['crossterm'] }